BazaSprzetu/BazaSprzetu/Models/ErrorViewModel.cs
using System;

namespace BazaSprzetu.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

BazaSprzetu/BazaSprzetu/Models/SprzetModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BazaSprzetu.Models
{
    public class SprzetModel
    {
        public int ID { get; set; }
        public string Rodzaj { get; set; }
        public string Producent { get; set; }
        public string Model { get; set; }
        public int Cena { get; set; }
    }
}

BazaSprzetu/BazaSprzetu/Controllers/HomeController.cs
using BazaSprzetu.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace BazaSprzetu.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

BazaSprzetu/BazaSprzetu/Controllers/SprzetController.cs
using BazaSprzetu.Logic;
using BazaSprzetu.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BazaSprzetu.Controllers
{
    public class SprzetController : Controller
    {
        SprzetManager sprzetManager = new SprzetManager();

        public IActionResult Index()
        {
            var sprzetList = sprzetManager.GetSprzets();
            return View(sprzetList);
        }


        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Add(SprzetModel sprzetModel)
        {
            sprzetManager.AddSprzet(sprzetModel);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Remove(int id)
        {
            var film = sprzetManager.GetSprzet(id);
            return View(film);
        }

        [HttpPost]
        public IActionResult RemoveConfirm(int id)
        {
            sprzetManager.RemoveSprzet(id);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult Edit(int id)
        {
            var film = sprzetManager.GetSprzet(id);
            return View(film);
        }

        [HttpPost]
        public IActionResult Edit(SprzetModel sprzet)
        {
            sprzetManager.UpdateSprzet(sprzet);
            return RedirectToAction("Index");
        }
    }
}

BazaSprzetu/BazaSprzetu/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BazaSprzetu</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Sprzet" asp-action="Index">Baza Sprzetu</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Sprzet" asp-action="Add">Dodaj sprzet</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - BazaSprzetu - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

BazaSprzetu/BazaSprzetu/Views/Sprzet/Add.cshtml
@model BazaSprzetu.Models.SprzetModel

@{
    ViewData["Title"] = "Add";
}

<h1>Dodaj</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Add">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Rodzaj" class="control-label"></label>
                <input asp-for="Rodzaj" class="form-control" />
                <span asp-validation-for="Rodzaj" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Producent" class="control-label"></label>
                <input asp-for="Producent" class="form-control" />
                <span asp-validation-for="Producent" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Model" class="control-label"></label>
                <input asp-for="Model" class="form-control" />
                <span asp-validation-for="Model" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cena" class="control-label"></label>
                <input asp-for="Cena" class="form-control" />
                <span asp-validation-for="Cena" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Dodaj" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" class="btn btn-secondary">Powrót na stronę główną</a>
</div>

BazaSprzetu/BazaSprzetu/Views/Sprzet/Edit.cshtml
@model BazaSprzetu.Models.SprzetModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edycja</h1>

<hr />
<div class="row">
    <div class="col-md-4">

        <h4>Dane sprzetu</h4>

        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Rodzaj" class="control-label"></label>
                <input asp-for="Rodzaj" class="form-control" />
                <span asp-validation-for="Rodzaj" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Producent" class="control-label"></label>
                <input asp-for="Producent" class="form-control" />
                <span asp-validation-for="Producent" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Model" class="control-label"></label>
                <input asp-for="Model" class="form-control" />
                <span asp-validation-for="Model" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cena" class="control-label"></label>
                <input asp-for="Cena" class="form-control" />
                <span asp-validation-for="Cena" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Zapisz" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" class="btn btn-secondary">Powrót na stronę główną</a>
</div>

BazaSprzetu/BazaSprzetu/Views/Sprzet/Index.cshtml
@model IEnumerable<BazaSprzetu.Models.SprzetModel>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Add"><button>Dodaj Sprzet</button></a>
</p>
<table class="table table-striped table-bordered">
    <thead class="thead-dark">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Rodzaj)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Producent)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Model)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Cena)
            </th>
            <th>
                <a>Akcja</a>
            </th>
            
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Rodzaj)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Producent)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Model)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Cena)
            </td>
            <td>
                | <a asp-action="Edit" asp-route-id="@item.ID">Edytuj</a> |
                <a asp-action="Remove" asp-route-id="@item.ID">Usun</a> |
            </td>
        </tr>
}
    </tbody>
</table>

BazaSprzetu/BazaSprzetu/Views/Sprzet/Remove.cshtml
@model BazaSprzetu.Models.SprzetModel

@{
    ViewData["Title"] = "Remove";
}

<h1>Remove</h1>

<p>Czy na pewno chcesz usunąć film o nazwie @Model.Model?</p>

<div>
    <form asp-action="RemoveConfirm">
        <input hidden value="@Model.ID" class="form-control" />
        <button class="btn btn-danger">Potwierdź usuniecie</button>

    </form>
    <a asp-action="Index" class="btn btn-secondary">Powrót na stronę główną</a>
</div>









<hr />
<div class="row">
    <div class="col-md-4">

        <h4>Dane sprzetu</h4>

        <form asp-action="Remove">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Rodzaj" class="control-label"></label>
                <input asp-for="Rodzaj" class="form-control" />
                <span asp-validation-for="Rodzaj" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Producent" class="control-label"></label>
                <input asp-for="Producent" class="form-control" />
                <span asp-validation-for="Producent" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Model" class="control-label"></label>
                <input asp-for="Model" class="form-control" />
                <span asp-validation-for="Model" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cena" class="control-label"></label>
                <input asp-for="Cena" class="form-control" />
                <span asp-validation-for="Cena" class="text-danger"></span>
            </div>

        </form>
    </div>
</div>